/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ucr.if4100.sqlaccess.gui;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import ucr.if4100.sqlaccess.business.concrete.AccountBiz;
import ucr.if4100.sqlaccess.business.concrete.AccountMovementBiz;
import ucr.if4100.sqlaccess.business.concrete.ClientBiz;
import ucr.if4100.sqlaccess.business.concrete.HasBiz;
import ucr.if4100.sqlaccess.business.concrete.MovementBiz;
import ucr.if4100.sqlaccess.business.concrete.TransferAccountBiz;
import ucr.if4100.sqlaccess.common.bean.account;
import ucr.if4100.sqlaccess.common.bean.client;
import ucr.if4100.sqlaccess.common.bean.has;
import ucr.if4100.sqlaccess.common.bean.movement;
import ucr.if4100.sqlaccess.common.bean.record;
import ucr.if4100.sqlaccess.data.AccountData;
import ucr.if4100.sqlaccess.data.ClientData;
import ucr.if4100.sqlaccess.data.HasData;

/**
 *
 * @author Wilmata
 */
public class CRUD extends javax.swing.JFrame {

    /**
     * Creates new form CRUD
     */
    public CRUD() {
        initComponents();
        fillClientsTable();
        fillAccountTable();
        fillMovementsTable();
    }
    ClientBiz clientBiz = new ClientBiz();
    AccountBiz accountBiz = new AccountBiz();
    HasBiz hasBiz = new HasBiz();
    MovementBiz movementBiz = new MovementBiz();
    AccountMovementBiz accountMovementBiz = new AccountMovementBiz();
    TransferAccountBiz transferAccountBiz = new TransferAccountBiz();
    DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd");
    LocalDateTime now = LocalDateTime.now();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void fillClientsTable() {
        List<client> client = clientBiz.getClients();
        if (client.size() > 0) {
            String[][] arrayTableClient = new String[client.size()][5];
            for (int i = 0; i < client.size(); i++) {
                arrayTableClient[i][0] = client.get(i).getId();
                arrayTableClient[i][1] = client.get(i).getFirstName();
                arrayTableClient[i][2] = client.get(i).getLastName();
                arrayTableClient[i][3] = client.get(i).getAddress();
                arrayTableClient[i][4] = client.get(i).getBirthdate();

                clientTable.setModel(new javax.swing.table.DefaultTableModel(arrayTableClient, new String[]{"ID", "First Name", "Last Name", "Address", "Birthday"}));
                accountClientsTable.setModel(new javax.swing.table.DefaultTableModel(arrayTableClient, new String[]{"ID", "First Name", "Last Name", "Address", "Birthday"}));
            }
        } else {
            String[][] arrayTableClient = new String[client.size()][5];
            clientTable.setModel(new javax.swing.table.DefaultTableModel(arrayTableClient, new String[]{"ID", "First Name", "Last Name", "Address", "Birthday"}));
            accountClientsTable.setModel(new javax.swing.table.DefaultTableModel(arrayTableClient, new String[]{"ID", "First Name", "Last Name", "Address", "Birthday"}));
        }
    }

    private void fillAccountTable() {
        List<account> account = accountBiz.getClients();
        if (account.size() > 0) {
            String[][] arrayTableAccount = new String[account.size()][4];
            for (int i = 0; i < account.size(); i++) {
                arrayTableAccount[i][0] = account.get(i).getId();
                arrayTableAccount[i][1] = account.get(i).getNumber();
                arrayTableAccount[i][2] = String.valueOf(account.get(i).getAccountBalance());
                arrayTableAccount[i][3] = account.get(i).getCurrency();

                accountTable.setModel(new javax.swing.table.DefaultTableModel(arrayTableAccount, new String[]{"No. Cuenta", "No. Interno", "Saldo", "Moneda"}));
                accountsMovementTable.setModel(new javax.swing.table.DefaultTableModel(arrayTableAccount, new String[]{"No. Cuenta", "No. Interno", "Saldo", "Moneda"}));
                accountsRecordsTable.setModel(new javax.swing.table.DefaultTableModel(arrayTableAccount, new String[]{"No. Cuenta", "No. Interno", "Saldo", "Moneda"}));
                fromTable.setModel(new javax.swing.table.DefaultTableModel(arrayTableAccount, new String[]{"No. Cuenta", "No. Interno", "Saldo", "Moneda"}));
                toTable.setModel(new javax.swing.table.DefaultTableModel(arrayTableAccount, new String[]{"No. Cuenta", "No. Interno", "Saldo", "Moneda"}));

            }
        } else {
            String[][] arrayTableAccount = new String[account.size()][4];
            accountTable.setModel(new javax.swing.table.DefaultTableModel(arrayTableAccount, new String[]{"No. Cuenta", "No. Interno", "Saldo", "Moneda"}));
            accountsMovementTable.setModel(new javax.swing.table.DefaultTableModel(arrayTableAccount, new String[]{"No. Cuenta", "No. Interno", "Saldo", "Moneda"}));
            accountsRecordsTable.setModel(new javax.swing.table.DefaultTableModel(arrayTableAccount, new String[]{"No. Cuenta", "No. Interno", "Saldo", "Moneda"}));
        }
    }

    private void fillRecordsTable() {
        List<record> recordsList = accountBiz.getRecordsByAccount(accountsRecordsTable.getValueAt(accountsRecordsTable.getSelectedRow(), 0).toString());

        if (recordsList.size() > 0) {
            String[][] arrayTableAccount = new String[recordsList.size()][7];
            for (int i = 0; i < recordsList.size(); i++) {
                arrayTableAccount[i][0] = recordsList.get(i).getId();
                arrayTableAccount[i][1] = recordsList.get(i).getNumber();
                arrayTableAccount[i][2] = recordsList.get(i).getCurrency();
                arrayTableAccount[i][3] = recordsList.get(i).getDate();
                arrayTableAccount[i][4] = recordsList.get(i).getDetail();
                arrayTableAccount[i][5] = recordsList.get(i).getAmount();
                arrayTableAccount[i][6] = recordsList.get(i).getClientName();

                recordsTable.setModel(new javax.swing.table.DefaultTableModel(arrayTableAccount, new String[]{"ID Cuenta", "No. Interno", "Moneda", "Fecha", "Detalle", "Monto", "Cliente"}));
            }
        } else {
            String[][] arrayTableAccount = new String[recordsList.size()][7];
            recordsTable.setModel(new javax.swing.table.DefaultTableModel(arrayTableAccount, new String[]{"ID Cuenta", "No. Interno", "Moneda", "Fecha", "Detalle", "Monto", "Cliente"}));
        }
    }

    private void fillMovementsTable() {
        List<movement> movement = movementBiz.getMovements();
        if (movement.size() > 0) {
            String[][] arrayTableMovement = new String[movement.size()][7];
            for (int i = 0; i < movement.size(); i++) {
                arrayTableMovement[i][0] = movement.get(i).getId();
                arrayTableMovement[i][1] = String.valueOf(movement.get(i).getAmount());
                arrayTableMovement[i][2] = movement.get(i).getDate();
                arrayTableMovement[i][3] = movement.get(i).getDetail();
                arrayTableMovement[i][4] = movement.get(i).getIdAccount();
                arrayTableMovement[i][5] = movement.get(i).getIdClient();
                arrayTableMovement[i][6] = movement.get(i).getClientName();
                movementTable.setModel(new javax.swing.table.DefaultTableModel(arrayTableMovement, new String[]{"ID", "Monto", "Fecha", "Detalle", "Cuenta Cliente", "ID Cliente", "Cliente"}));

            }
        } else {
            String[][] arrayTableMovement = new String[movement.size()][7];
            movementTable.setModel(new javax.swing.table.DefaultTableModel(arrayTableMovement, new String[]{"ID", "Monto", "Fecha", "Detalle", "Cuenta Cliente", "ID Cliente", "Cliente"}));
        }
    }

    public has getHasClientByID(String idAccount) {
        List<has> hasList = hasBiz.getHas();
        has hasObject = new has();
        if (hasList.size() > 0) {
            for (int i = 0; i < hasList.size(); i++) {
                if (idAccount.equals(hasList.get(i).getIdAccount())) {
                    return hasList.get(i);
                }
            }
        }

        return hasObject;
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane13 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jScrollPane14 = new javax.swing.JScrollPane();
        jTable6 = new javax.swing.JTable();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        insertAccount = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        insertInterno = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        monedaComboBox = new javax.swing.JComboBox<>();
        jSeparator3 = new javax.swing.JSeparator();
        insertAccountButton = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jScrollPane9 = new javax.swing.JScrollPane();
        accountTable = new javax.swing.JTable();
        jScrollPane10 = new javax.swing.JScrollPane();
        accountClientsTable = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        labelAccountClient = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jButton4 = new javax.swing.JButton();
        borrarButton = new javax.swing.JButton();
        jScrollPane11 = new javax.swing.JScrollPane();
        clientTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        insertCedulaTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        insertNombreTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        insertApellidosTextField = new javax.swing.JTextField();
        insertDireccionTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        insertFechaTextField = new javax.swing.JTextField();
        insertClientButton = new javax.swing.JButton();
        updateClientButton = new javax.swing.JButton();
        usuarioMsgLabel = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel26 = new javax.swing.JLabel();
        drFondosLabel = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        drIDLabel = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        montoTextField = new javax.swing.JTextField();
        accionButton = new javax.swing.JButton();
        jScrollPane18 = new javax.swing.JScrollPane();
        movementTable = new javax.swing.JTable();
        drMontoLabel = new javax.swing.JLabel();
        jScrollPane19 = new javax.swing.JScrollPane();
        accountsMovementTable = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        ID = new javax.swing.JLabel();
        drFechaLabel = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        drDetalleLabel = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        drCuentaLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        drClienteLabel = new javax.swing.JLabel();
        accionComboBox = new javax.swing.JComboBox<>();
        transaccionTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        detalleTextField = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        drCuenta1Label = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        accountsRecordsTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        recordsTable = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        transferMontoTextField = new javax.swing.JTextField();
        jButton14 = new javax.swing.JButton();
        jScrollPane12 = new javax.swing.JScrollPane();
        toTable = new javax.swing.JTable();
        jScrollPane15 = new javax.swing.JScrollPane();
        fromTable = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        transferClientIDLabel = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        tranferCurrencyLabel = new javax.swing.JLabel();
        transferClientNameLabel = new javax.swing.JLabel();
        msgLabel = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        idTransfertextField = new javax.swing.JTextField();
        Detalle = new javax.swing.JLabel();
        tranferDetalleTextField = new javax.swing.JTextField();

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane13.setViewportView(jTable5);

        jTable6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane14.setViewportView(jTable6);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBackground(new java.awt.Color(198, 239, 255));

        jPanel8.setBackground(new java.awt.Color(229, 240, 246));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setText("Número de cuenta");
        jPanel8.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));
        jPanel8.add(insertAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 110, -1));

        jLabel12.setText("Número interno");
        jPanel8.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));
        jPanel8.add(insertInterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 110, -1));

        jLabel13.setText("Tipo de moneda");
        jPanel8.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        monedaComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Colones", "Dólares", "Euros" }));
        jPanel8.add(monedaComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 110, -1));

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel8.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 17, 389));

        insertAccountButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\wilme\\Desktop\\IIIBases\\tareaArqui\\src\\main\\java\\images\\simbolo-mas-en-un-cuadrado-negro-redondeado.png")); // NOI18N
        insertAccountButton.setContentAreaFilled(false);
        insertAccountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertAccountButtonActionPerformed(evt);
            }
        });
        jPanel8.add(insertAccountButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, -1, -1));

        jButton7.setIcon(new javax.swing.ImageIcon("C:\\Users\\wilme\\Desktop\\IIIBases\\tareaArqui\\src\\main\\java\\images\\borrar.png")); // NOI18N
        jButton7.setContentAreaFilled(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, -1));

        accountTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        accountTable.setFillsViewportHeight(true);
        accountTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                accountTableMouseClicked(evt);
            }
        });
        jScrollPane9.setViewportView(accountTable);

        jPanel8.add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 510, 100));

        accountClientsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        accountClientsTable.setFillsViewportHeight(true);
        accountClientsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                accountClientsTableMouseClicked(evt);
            }
        });
        jScrollPane10.setViewportView(accountClientsTable);

        jPanel8.add(jScrollPane10, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 510, 100));

        jLabel6.setText("Cliente");
        jPanel8.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        labelAccountClient.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel8.add(labelAccountClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 130, 20));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 680, Short.MAX_VALUE)
            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Cuentas", jPanel3);

        jPanel2.setBackground(new java.awt.Color(229, 240, 246));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(229, 240, 246));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 0, -1, 449));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 17, 398));

        jButton4.setText("Borrar");
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(935, 350, -1, -1));

        borrarButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\wilme\\Desktop\\IIIBases\\tareaArqui\\src\\main\\java\\images\\borrar.png")); // NOI18N
        borrarButton.setContentAreaFilled(false);
        borrarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarButtonActionPerformed(evt);
            }
        });
        jPanel2.add(borrarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 320, -1, -1));

        clientTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        clientTable.setFillsViewportHeight(true);
        clientTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clientTableMouseClicked(evt);
            }
        });
        jScrollPane11.setViewportView(clientTable);

        jPanel2.add(jScrollPane11, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 450, 270));

        jLabel1.setText("Cédula");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        insertCedulaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertCedulaTextFieldActionPerformed(evt);
            }
        });
        jPanel2.add(insertCedulaTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 137, -1));

        jLabel2.setText("Nombre");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        insertNombreTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertNombreTextFieldActionPerformed(evt);
            }
        });
        jPanel2.add(insertNombreTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 137, -1));

        jLabel3.setText("Apellidos");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));
        jPanel2.add(insertApellidosTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 137, -1));
        jPanel2.add(insertDireccionTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 137, -1));

        jLabel4.setText("Dirección");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jLabel5.setText("Fecha de nacimiento");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));
        jPanel2.add(insertFechaTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 137, -1));

        insertClientButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\wilme\\Desktop\\IIIBases\\tareaArqui\\src\\main\\java\\images\\simbolo-mas-en-un-cuadrado-negro-redondeado.png")); // NOI18N
        insertClientButton.setContentAreaFilled(false);
        insertClientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertClientButtonActionPerformed(evt);
            }
        });
        jPanel2.add(insertClientButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));

        updateClientButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\wilme\\Desktop\\IIIBases\\tareaArqui\\src\\main\\java\\images\\intercambio.png")); // NOI18N
        updateClientButton.setContentAreaFilled(false);
        updateClientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateClientButtonActionPerformed(evt);
            }
        });
        jPanel2.add(updateClientButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, -1, -1));
        jPanel2.add(usuarioMsgLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 200, 20));

        jTabbedPane1.addTab("Usuarios", jPanel2);

        jPanel4.setBackground(new java.awt.Color(229, 240, 246));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel4.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, -1, 90));

        jLabel26.setText("ID:");
        jPanel4.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 40, 20));
        jPanel4.add(drFondosLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 100, 20));

        jLabel28.setText("Fondos");
        jPanel4.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));
        jPanel4.add(drIDLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 200, 20));

        jLabel30.setText("Monto:");
        jPanel4.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, 20));
        jPanel4.add(montoTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 90, -1));

        accionButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\wilme\\Desktop\\IIIBases\\tareaArqui\\src\\main\\java\\images\\comprobado.png")); // NOI18N
        accionButton.setContentAreaFilled(false);
        accionButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                accionButtonMouseClicked(evt);
            }
        });
        accionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accionButtonActionPerformed(evt);
            }
        });
        jPanel4.add(accionButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, -1, -1));

        movementTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        movementTable.setFillsViewportHeight(true);
        movementTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                movementTableMouseClicked(evt);
            }
        });
        jScrollPane18.setViewportView(movementTable);

        jPanel4.add(jScrollPane18, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 380, 180));
        jPanel4.add(drMontoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 170, 20));

        accountsMovementTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        accountsMovementTable.setFillsViewportHeight(true);
        accountsMovementTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                accountsMovementTableMouseClicked(evt);
            }
        });
        jScrollPane19.setViewportView(accountsMovementTable);

        jPanel4.add(jScrollPane19, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 380, 180));
        jPanel4.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, -1, -1));

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel4.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 60, 420));

        ID.setText("Fecha:");
        jPanel4.add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, 20));
        jPanel4.add(drFechaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 160, 20));

        jLabel8.setText("Detalle:");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, 20));
        jPanel4.add(drDetalleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 160, 20));

        jLabel10.setText("Cuenta:");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, 20));
        jPanel4.add(drCuentaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, 150, 20));

        jLabel7.setText("Cliente:");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, -1, 20));
        jPanel4.add(drClienteLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, 160, 20));

        accionComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Depósito", "Retiro" }));
        jPanel4.add(accionComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 90, -1));
        jPanel4.add(transaccionTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 90, -1));

        jLabel9.setText("No. Transacción");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel14.setText("Monto");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, -1, -1));
        jPanel4.add(detalleTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 120, -1));

        jLabel15.setText("Detalle");
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jLabel16.setText("Cuenta");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));
        jPanel4.add(drCuenta1Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 140, 20));

        jTabbedPane1.addTab("Depósito/Retiro", jPanel4);

        jPanel11.setBackground(new java.awt.Color(229, 240, 246));

        accountsRecordsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        accountsRecordsTable.setFillsViewportHeight(true);
        accountsRecordsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                accountsRecordsTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(accountsRecordsTable);

        recordsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Cuenta", "No. Interno", "Moneda", "Fecha", "Detalle", "Monto", "Cliente"
            }
        ));
        recordsTable.setFillsViewportHeight(true);
        jScrollPane2.setViewportView(recordsTable);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Estado de cuenta", jPanel9);

        jPanel5.setBackground(new java.awt.Color(229, 240, 246));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel31.setText("Monto");
        jPanel5.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 350, -1, -1));
        jPanel5.add(transferMontoTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 350, 160, -1));

        jButton14.setIcon(new javax.swing.ImageIcon("C:\\Users\\wilme\\Desktop\\IIIBases\\tareaArqui\\src\\main\\java\\images\\comprobado.png")); // NOI18N
        jButton14.setContentAreaFilled(false);
        jButton14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton14MouseClicked(evt);
            }
        });
        jPanel5.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 340, -1, -1));

        toTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        toTable.setFillsViewportHeight(true);
        jScrollPane12.setViewportView(toTable);

        jPanel5.add(jScrollPane12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 630, 95));

        fromTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        fromTable.setFillsViewportHeight(true);
        fromTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fromTableMouseClicked(evt);
            }
        });
        jScrollPane15.setViewportView(fromTable);

        jPanel5.add(jScrollPane15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 630, 95));

        jLabel17.setText("Cliente");
        jPanel5.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, 20));
        jPanel5.add(transferClientIDLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 70, 20));

        jLabel19.setText("Moneda");
        jPanel5.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, 20));
        jPanel5.add(tranferCurrencyLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 100, 20));
        jPanel5.add(transferClientNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 150, 20));
        jPanel5.add(msgLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 380, 250, 20));

        jLabel18.setText("ID Transferencia");
        jPanel5.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, -1, -1));
        jPanel5.add(idTransfertextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, 140, -1));

        Detalle.setText("Detalle");
        jPanel5.add(Detalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, -1, -1));
        jPanel5.add(tranferDetalleTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, 140, -1));

        jTabbedPane1.addTab("Transferencias", jPanel5);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 685, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void accountsMovementTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountsMovementTableMouseClicked
        drCuenta1Label.setText(accountsMovementTable.getValueAt(accountsMovementTable.getSelectedRow(), 0).toString());
        drFondosLabel.setText(accountsMovementTable.getValueAt(accountsMovementTable.getSelectedRow(), 2).toString());
    }//GEN-LAST:event_accountsMovementTableMouseClicked

    private void movementTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_movementTableMouseClicked
        has hasClient = getHasClientByID(movementTable.getValueAt(movementTable.getSelectedRow(), 0).toString());
        drIDLabel.setText(movementTable.getValueAt(movementTable.getSelectedRow(), 0).toString());
        drMontoLabel.setText(movementTable.getValueAt(movementTable.getSelectedRow(), 1).toString());
        drFechaLabel.setText(movementTable.getValueAt(movementTable.getSelectedRow(), 2).toString());
        drDetalleLabel.setText(movementTable.getValueAt(movementTable.getSelectedRow(), 3).toString());
        drCuentaLabel.setText(movementTable.getValueAt(movementTable.getSelectedRow(), 4).toString());
        drClienteLabel.setText(hasClient.getNameClient());
    }//GEN-LAST:event_movementTableMouseClicked

    private void accionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accionButtonActionPerformed

    }//GEN-LAST:event_accionButtonActionPerformed

    private void updateClientButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateClientButtonActionPerformed
        clientBiz.updateClient(insertCedulaTextField.getText().toString(), insertNombreTextField.getText().toString(), insertApellidosTextField.getText().toString(), insertDireccionTextField.getText().toString(), insertFechaTextField.getText().toString());
        fillClientsTable();
    }//GEN-LAST:event_updateClientButtonActionPerformed

    private void insertClientButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertClientButtonActionPerformed
        if (insertCedulaTextField.getText().toString().equalsIgnoreCase("") || insertNombreTextField.getText().toString().equalsIgnoreCase("") || insertApellidosTextField.getText().toString().equalsIgnoreCase("") || insertDireccionTextField.getText().toString().equalsIgnoreCase("") || insertFechaTextField.getText().toString().equalsIgnoreCase("")) {
            usuarioMsgLabel.setText("Ingrese todos los espacios.");
        } else {
            clientBiz.insertClient(insertCedulaTextField.getText().toString(), insertNombreTextField.getText().toString(), insertApellidosTextField.getText().toString(), insertDireccionTextField.getText().toString(), insertFechaTextField.getText().toString());
            fillClientsTable();
            usuarioMsgLabel.setText("Cliente registrado correctamente.");
        }
    }//GEN-LAST:event_insertClientButtonActionPerformed

    private void insertNombreTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertNombreTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_insertNombreTextFieldActionPerformed

    private void insertCedulaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertCedulaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_insertCedulaTextFieldActionPerformed

    private void clientTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clientTableMouseClicked
        insertCedulaTextField.setText(clientTable.getValueAt(clientTable.getSelectedRow(), 0).toString().toString());
        insertNombreTextField.setText(clientTable.getValueAt(clientTable.getSelectedRow(), 1).toString().toString());
        insertApellidosTextField.setText(clientTable.getValueAt(clientTable.getSelectedRow(), 2).toString().toString());
        insertDireccionTextField.setText(clientTable.getValueAt(clientTable.getSelectedRow(), 3).toString().toString());
        insertFechaTextField.setText(clientTable.getValueAt(clientTable.getSelectedRow(), 4).toString().toString());
    }//GEN-LAST:event_clientTableMouseClicked

    private void borrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarButtonActionPerformed
        hasBiz.deleteHasByIdClient(insertCedulaTextField.getText().toString());
        clientBiz.deleteClient(insertCedulaTextField.getText().toString());
        List<has> hasList = hasBiz.getHas();
        for (int i = 0; i < hasList.size(); i++) {
            if (insertCedulaTextField.getText().toString().equalsIgnoreCase(hasList.get(i).getIdClient())) {
                accountBiz.deleteAccountById(hasList.get(i).getIdAccount());
            }
        }
        fillClientsTable();
    }//GEN-LAST:event_borrarButtonActionPerformed

    private void accountClientsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountClientsTableMouseClicked
        labelAccountClient.setText(accountClientsTable.getValueAt(accountClientsTable.getSelectedRow(), 1).toString() + " " + accountClientsTable.getValueAt(accountClientsTable.getSelectedRow(), 2).toString());
    }//GEN-LAST:event_accountClientsTableMouseClicked

    private void accountTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountTableMouseClicked
        labelAccountClient.setText(" ");
        List<has> hasList = hasBiz.getHas();

        for (int i = 0; i < hasList.size(); i++) {
            if (hasList.get(i).getIdAccount().equals(accountTable.getValueAt(accountTable.getSelectedRow(), 0).toString())) {
                labelAccountClient.setText(hasList.get(i).getNameClient());
            }
        }
    }//GEN-LAST:event_accountTableMouseClicked

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        hasBiz.deleteHasByIdAccount(accountTable.getValueAt(accountTable.getSelectedRow(), 0).toString());
        accountBiz.deleteAccountById(accountTable.getValueAt(accountTable.getSelectedRow(), 0).toString());

        fillAccountTable();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void insertAccountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertAccountButtonActionPerformed
        accountBiz.insertAccount(insertAccount.getText().toString(), insertInterno.getText().toString(), 0, monedaComboBox.getSelectedItem().toString());
        hasBiz.insertHas(accountClientsTable.getValueAt(accountClientsTable.getSelectedRow(), 0).toString(),
                accountClientsTable.getValueAt(accountClientsTable.getSelectedRow(), 1).toString() + " "
                + accountClientsTable.getValueAt(accountClientsTable.getSelectedRow(), 2).toString(),
                insertAccount.getText().toString(),
                insertInterno.getText().toString());
        fillAccountTable();
    }//GEN-LAST:event_insertAccountButtonActionPerformed

    private void accountsRecordsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountsRecordsTableMouseClicked
        fillRecordsTable();
    }//GEN-LAST:event_accountsRecordsTableMouseClicked

    private void accionButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accionButtonMouseClicked
        if (accionComboBox.getSelectedItem().toString().equalsIgnoreCase("depósito")) {
            has hasClient = getHasClientByID(accountsMovementTable.getValueAt(accountsMovementTable.getSelectedRow(), 0).toString());
            accountMovementBiz.makeDesposit(transaccionTextField.getText().toString(),
                    Integer.parseInt(montoTextField.getText().toString()), now.toString(),
                    "Depósito: " + detalleTextField.getText().toString(),
                    accountsMovementTable.getValueAt(accountsMovementTable.getSelectedRow(), 0).toString(),
                    accountsMovementTable.getValueAt(accountsMovementTable.getSelectedRow(), 1).toString(),
                    hasClient.getIdClient().toString(),
                    hasClient.getNameClient().toString(),
                    accountsMovementTable.getValueAt(accountsMovementTable.getSelectedRow(), 3).toString());
            fillMovementsTable();
            fillAccountTable();
        } else {
            has hasClient = getHasClientByID(accountsMovementTable.getValueAt(accountsMovementTable.getSelectedRow(), 0).toString());
            accountMovementBiz.makeWithdrawal(transaccionTextField.getText().toString(),
                    Integer.parseInt(montoTextField.getText().toString()), now.toString(),
                    "Retiro: " + detalleTextField.getText().toString(),
                    accountsMovementTable.getValueAt(accountsMovementTable.getSelectedRow(), 0).toString(),
                    accountsMovementTable.getValueAt(accountsMovementTable.getSelectedRow(), 1).toString(),
                    hasClient.getIdClient().toString(),
                    hasClient.getNameClient().toString(),
                    accountsMovementTable.getValueAt(accountsMovementTable.getSelectedRow(), 3).toString());
            fillMovementsTable();
            fillAccountTable();
        }
    }//GEN-LAST:event_accionButtonMouseClicked

    private void fromTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fromTableMouseClicked
        has hasClient = getHasClientByID(fromTable.getValueAt(fromTable.getSelectedRow(), 0).toString());
        transferClientIDLabel.setText(hasClient.getIdClient());
        transferClientNameLabel.setText(hasClient.getNameClient());
        tranferCurrencyLabel.setText(fromTable.getValueAt(fromTable.getSelectedRow(), 3).toString());
    }//GEN-LAST:event_fromTableMouseClicked

    private void jButton14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton14MouseClicked
        if (Integer.parseInt(fromTable.getValueAt(fromTable.getSelectedRow(), 2).toString()) > 0 && fromTable.getValueAt(fromTable.getSelectedRow(), 3).toString().equalsIgnoreCase(toTable.getValueAt(toTable.getSelectedRow(), 3).toString())) {
            transferAccountBiz.makeTransfer(idTransfertextField.getText().toString(),
                     transferMontoTextField.getText().toString(),
                     now.toString(),
                     tranferDetalleTextField.getText().toString(),
                     fromTable.getValueAt(fromTable.getSelectedRow(), 0).toString(),
                     toTable.getValueAt(toTable.getSelectedRow(), 0).toString(),
                     fromTable.getValueAt(fromTable.getSelectedRow(), 1).toString(),
                     toTable.getValueAt(toTable.getSelectedRow(), 1).toString(),
                     transferClientIDLabel.getText().toString(),
                     transferClientNameLabel.getText().toString(),
                     tranferCurrencyLabel.getText());
            msgLabel.setText("Tranferencia realizada.");
            fillAccountTable();
        } else {
            msgLabel.setText("Tipo de moneda diferente.");
        }
    }//GEN-LAST:event_jButton14MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CRUD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Detalle;
    private javax.swing.JLabel ID;
    private javax.swing.JButton accionButton;
    private javax.swing.JComboBox<String> accionComboBox;
    private javax.swing.JTable accountClientsTable;
    private javax.swing.JTable accountTable;
    private javax.swing.JTable accountsMovementTable;
    private javax.swing.JTable accountsRecordsTable;
    private javax.swing.JButton borrarButton;
    private javax.swing.JTable clientTable;
    private javax.swing.JTextField detalleTextField;
    private javax.swing.JLabel drClienteLabel;
    private javax.swing.JLabel drCuenta1Label;
    private javax.swing.JLabel drCuentaLabel;
    private javax.swing.JLabel drDetalleLabel;
    private javax.swing.JLabel drFechaLabel;
    private javax.swing.JLabel drFondosLabel;
    private javax.swing.JLabel drIDLabel;
    private javax.swing.JLabel drMontoLabel;
    private javax.swing.JTable fromTable;
    private javax.swing.JTextField idTransfertextField;
    private javax.swing.JTextField insertAccount;
    private javax.swing.JButton insertAccountButton;
    private javax.swing.JTextField insertApellidosTextField;
    private javax.swing.JTextField insertCedulaTextField;
    private javax.swing.JButton insertClientButton;
    private javax.swing.JTextField insertDireccionTextField;
    private javax.swing.JTextField insertFechaTextField;
    private javax.swing.JTextField insertInterno;
    private javax.swing.JTextField insertNombreTextField;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane18;
    private javax.swing.JScrollPane jScrollPane19;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable5;
    private javax.swing.JTable jTable6;
    private javax.swing.JLabel labelAccountClient;
    private javax.swing.JComboBox<String> monedaComboBox;
    private javax.swing.JTextField montoTextField;
    private javax.swing.JTable movementTable;
    private javax.swing.JLabel msgLabel;
    private javax.swing.JTable recordsTable;
    private javax.swing.JTable toTable;
    private javax.swing.JLabel tranferCurrencyLabel;
    private javax.swing.JTextField tranferDetalleTextField;
    private javax.swing.JTextField transaccionTextField;
    private javax.swing.JLabel transferClientIDLabel;
    private javax.swing.JLabel transferClientNameLabel;
    private javax.swing.JTextField transferMontoTextField;
    private javax.swing.JButton updateClientButton;
    private javax.swing.JLabel usuarioMsgLabel;
    // End of variables declaration//GEN-END:variables
}
