/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ucr.if4100.sqlaccess.gui;

import java.util.List;
import ucr.if4100.sqlaccess.business.concrete.AccountBiz;
import ucr.if4100.sqlaccess.business.concrete.ClientBiz;
import ucr.if4100.sqlaccess.business.concrete.HasBiz;
import ucr.if4100.sqlaccess.business.concrete.MovementBiz;
import ucr.if4100.sqlaccess.common.bean.account;
import ucr.if4100.sqlaccess.common.bean.client;
import ucr.if4100.sqlaccess.common.bean.has;
import ucr.if4100.sqlaccess.common.bean.movement;
import ucr.if4100.sqlaccess.data.AccountData;
import ucr.if4100.sqlaccess.data.ClientData;
import ucr.if4100.sqlaccess.data.HasData;

/**
 *
 * @author Wilmata
 */
public class CRUD extends javax.swing.JFrame {

    /**
     * Creates new form CRUD
     */
    public CRUD() {
        initComponents();
        fillClientsTable();
        fillAccountTable();
        fillMovementsTable();
    }
    ClientBiz clientBiz = new ClientBiz();
    AccountBiz accountBiz = new AccountBiz();
    HasBiz hasBiz = new HasBiz();
    MovementBiz movementBiz = new MovementBiz();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void fillClientsTable() {
        List<client> client = clientBiz.getClients();
        if (client.size() > 0) {
            String[][] arrayTableClient = new String[client.size()][5];
            for (int i = 0; i < client.size(); i++) {
                arrayTableClient[i][0] = client.get(i).getId();
                arrayTableClient[i][1] = client.get(i).getFirstName();
                arrayTableClient[i][2] = client.get(i).getLastName();
                arrayTableClient[i][3] = client.get(i).getAddress();
                arrayTableClient[i][4] = client.get(i).getBirthdate();

                clientTable.setModel(new javax.swing.table.DefaultTableModel(arrayTableClient, new String[]{"ID", "First Name", "Last Name", "Address", "Birthday"}));
                accountClientsTable.setModel(new javax.swing.table.DefaultTableModel(arrayTableClient, new String[]{"ID", "First Name", "Last Name", "Address", "Birthday"}));
            }
        } else {
            String[][] arrayTableClient = new String[client.size()][5];
            clientTable.setModel(new javax.swing.table.DefaultTableModel(arrayTableClient, new String[]{"ID", "First Name", "Last Name", "Address", "Birthday"}));
            accountClientsTable.setModel(new javax.swing.table.DefaultTableModel(arrayTableClient, new String[]{"ID", "First Name", "Last Name", "Address", "Birthday"}));
        }
    }

    private void fillAccountTable() {
        List<account> account = accountBiz.getClients();
        if (account.size() > 0) {
            String[][] arrayTableAccount = new String[account.size()][4];
            for (int i = 0; i < account.size(); i++) {
                arrayTableAccount[i][0] = account.get(i).getId();
                arrayTableAccount[i][1] = account.get(i).getNumber();
                arrayTableAccount[i][2] = String.valueOf(account.get(i).getAccountBalance());
                arrayTableAccount[i][3] = account.get(i).getCurrency();

                accountTable.setModel(new javax.swing.table.DefaultTableModel(arrayTableAccount, new String[]{"No. Cuenta", "No. Interno", "Saldo", "Moneda"}));
                accountsMovementTable.setModel(new javax.swing.table.DefaultTableModel(arrayTableAccount, new String[]{"No. Cuenta", "No. Interno", "Saldo", "Moneda"}));

            }
        } else {
            String[][] arrayTableAccount = new String[account.size()][4];
            accountTable.setModel(new javax.swing.table.DefaultTableModel(arrayTableAccount, new String[]{"No. Cuenta", "No. Interno", "Saldo", "Moneda"}));
            accountsMovementTable.setModel(new javax.swing.table.DefaultTableModel(arrayTableAccount, new String[]{"No. Cuenta", "No. Interno", "Saldo", "Moneda"}));

        }
    }

    private void fillMovementsTable() {
        List<movement> movement = movementBiz.getMovements();
        if (movement.size() > 0) {
            String[][] arrayTableMovement = new String[movement.size()][7];
            for (int i = 0; i < movement.size(); i++) {
                arrayTableMovement[i][0] = movement.get(i).getId();
                arrayTableMovement[i][1] = String.valueOf(movement.get(i).getAmount());
                arrayTableMovement[i][2] = movement.get(i).getDate();
                arrayTableMovement[i][3] = movement.get(i).getDetail();
                arrayTableMovement[i][4] = movement.get(i).getIdAccount();
                arrayTableMovement[i][5] = movement.get(i).getIdClient();
                arrayTableMovement[i][6] = movement.get(i).getClientName();

                movementTable.setModel(new javax.swing.table.DefaultTableModel(arrayTableMovement, new String[]{"ID", "Monto", "Fecha", "Detalle", "Cuenta Cliente", "Cliente"}));

            }
        } else {
            String[][] arrayTableMovement = new String[movement.size()][5];
            movementTable.setModel(new javax.swing.table.DefaultTableModel(arrayTableMovement, new String[]{"ID", "Monto", "Fecha", "Detalle", "Cuenta Cliente", "Cliente"}));
        }
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane13 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jScrollPane14 = new javax.swing.JScrollPane();
        jTable6 = new javax.swing.JTable();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        insertAccount = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        insertInterno = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        monedaComboBox = new javax.swing.JComboBox<>();
        jSeparator3 = new javax.swing.JSeparator();
        insertAccountButton = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jScrollPane9 = new javax.swing.JScrollPane();
        accountTable = new javax.swing.JTable();
        jScrollPane10 = new javax.swing.JScrollPane();
        accountClientsTable = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        labelAccountClient = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jTextField19 = new javax.swing.JTextField();
        jButton14 = new javax.swing.JButton();
        jScrollPane12 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jScrollPane15 = new javax.swing.JScrollPane();
        jTable7 = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jButton15 = new javax.swing.JButton();
        jScrollPane16 = new javax.swing.JScrollPane();
        jTable8 = new javax.swing.JTable();
        jScrollPane17 = new javax.swing.JScrollPane();
        jTable9 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jButton4 = new javax.swing.JButton();
        borrarButton = new javax.swing.JButton();
        jScrollPane11 = new javax.swing.JScrollPane();
        clientTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        insertCedulaTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        insertNombreTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        insertApellidosTextField = new javax.swing.JTextField();
        insertDireccionTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        insertFechaTextField = new javax.swing.JTextField();
        insertClientButton = new javax.swing.JButton();
        updateClientButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        drIDLabel = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jTextField18 = new javax.swing.JTextField();
        accionButton = new javax.swing.JButton();
        jScrollPane18 = new javax.swing.JScrollPane();
        movementTable = new javax.swing.JTable();
        drMontoLabel = new javax.swing.JLabel();
        jScrollPane19 = new javax.swing.JScrollPane();
        accountsMovementTable = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        ID = new javax.swing.JLabel();
        drFechaLabel = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        drDetalleLabel = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        drCuentaLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        drClienteLabel = new javax.swing.JLabel();

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane13.setViewportView(jTable5);

        jTable6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane14.setViewportView(jTable6);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBackground(new java.awt.Color(198, 239, 255));

        jPanel8.setBackground(new java.awt.Color(229, 240, 246));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setText("Número de cuenta");
        jPanel8.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));
        jPanel8.add(insertAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 110, -1));

        jLabel12.setText("Número interno");
        jPanel8.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));
        jPanel8.add(insertInterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 110, -1));

        jLabel13.setText("Tipo de moneda");
        jPanel8.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        monedaComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Colones", "Dólares", "Euros" }));
        jPanel8.add(monedaComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 110, -1));

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel8.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 17, 389));

        insertAccountButton.setText("Agregar");
        insertAccountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertAccountButtonActionPerformed(evt);
            }
        });
        jPanel8.add(insertAccountButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, -1, -1));

        jButton7.setText("Borrar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, -1, -1));

        accountTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        accountTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                accountTableMouseClicked(evt);
            }
        });
        jScrollPane9.setViewportView(accountTable);

        jPanel8.add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 510, 100));

        accountClientsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        accountClientsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                accountClientsTableMouseClicked(evt);
            }
        });
        jScrollPane10.setViewportView(accountClientsTable);

        jPanel8.add(jScrollPane10, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 510, 100));

        jLabel6.setText("Cliente");
        jPanel8.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        labelAccountClient.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel8.add(labelAccountClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 130, 20));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 680, Short.MAX_VALUE)
            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Cuentas", jPanel3);

        jPanel5.setBackground(new java.awt.Color(229, 240, 246));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel31.setText("Monto");
        jPanel5.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 370, -1, -1));
        jPanel5.add(jTextField19, new org.netbeans.lib.awtextra.AbsoluteConstraints(413, 370, 160, -1));

        jButton14.setText("Aceptar");
        jPanel5.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 370, -1, -1));

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane12.setViewportView(jTable4);

        jPanel5.add(jScrollPane12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 630, 95));

        jTable7.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane15.setViewportView(jTable7);

        jPanel5.add(jScrollPane15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 630, 95));

        jTabbedPane1.addTab("Transferencias", jPanel5);

        jPanel6.setBackground(new java.awt.Color(229, 240, 246));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel32.setText("Cuentas");
        jPanel6.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 23, -1, -1));

        jLabel33.setText("Movimientos");
        jPanel6.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(333, 23, -1, -1));

        jLabel34.setText("Cliente");
        jPanel6.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(333, 213, -1, -1));

        jLabel35.setText("jLabel35");
        jPanel6.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(333, 233, 177, -1));

        jLabel36.setText("Saldo");
        jPanel6.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(333, 253, -1, -1));

        jLabel37.setText("jLabel37");
        jPanel6.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(333, 273, 177, -1));

        jButton15.setText("Reporte");
        jPanel6.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(554, 347, -1, -1));

        jTable8.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane16.setViewportView(jTable8);

        jPanel6.add(jScrollPane16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 290, 95));

        jTable9.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane17.setViewportView(jTable9);

        jPanel6.add(jScrollPane17, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, 330, 100));

        jTabbedPane1.addTab("Estado de cuenta", jPanel6);

        jPanel2.setBackground(new java.awt.Color(229, 240, 246));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(229, 240, 246));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 0, -1, 449));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 11, 17, 398));

        jButton4.setText("Borrar");
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(935, 350, -1, -1));

        borrarButton.setText("Borrar");
        borrarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarButtonActionPerformed(evt);
            }
        });
        jPanel2.add(borrarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 340, -1, -1));

        clientTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        clientTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clientTableMouseClicked(evt);
            }
        });
        jScrollPane11.setViewportView(clientTable);

        jPanel2.add(jScrollPane11, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 450, 270));

        jLabel1.setText("Cédula");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        insertCedulaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertCedulaTextFieldActionPerformed(evt);
            }
        });
        jPanel2.add(insertCedulaTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 137, -1));

        jLabel2.setText("Nombre");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        insertNombreTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertNombreTextFieldActionPerformed(evt);
            }
        });
        jPanel2.add(insertNombreTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 137, -1));

        jLabel3.setText("Apellidos");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));
        jPanel2.add(insertApellidosTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 137, -1));
        jPanel2.add(insertDireccionTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 137, -1));

        jLabel4.setText("Dirección");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jLabel5.setText("Fecha de nacimiento");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));
        jPanel2.add(insertFechaTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 137, -1));

        insertClientButton.setText("Agregar");
        insertClientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertClientButtonActionPerformed(evt);
            }
        });
        jPanel2.add(insertClientButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        updateClientButton.setText("Actualizar");
        updateClientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateClientButtonActionPerformed(evt);
            }
        });
        jPanel2.add(updateClientButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, -1, -1));

        jTabbedPane1.addTab("Usuarios", jPanel2);

        jPanel4.setBackground(new java.awt.Color(229, 240, 246));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel4.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, -1, 90));

        jLabel26.setText("ID");
        jPanel4.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 60, 20));
        jPanel4.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 150, 20));

        jLabel28.setText("Fondos");
        jPanel4.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));
        jPanel4.add(drIDLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 200, 20));

        jLabel30.setText("Monto");
        jPanel4.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, 10));
        jPanel4.add(jTextField18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 140, -1));

        accionButton.setText("Depósito");
        jPanel4.add(accionButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, -1, -1));

        movementTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        movementTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                movementTableMouseClicked(evt);
            }
        });
        jScrollPane18.setViewportView(movementTable);

        jPanel4.add(jScrollPane18, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 380, 180));
        jPanel4.add(drMontoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 170, 20));

        accountsMovementTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        accountsMovementTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                accountsMovementTableMouseClicked(evt);
            }
        });
        jScrollPane19.setViewportView(accountsMovementTable);

        jPanel4.add(jScrollPane19, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 380, 180));
        jPanel4.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, -1, -1));

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel4.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 60, 420));

        ID.setText("Fecha");
        jPanel4.add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));
        jPanel4.add(drFechaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 160, 20));

        jLabel8.setText("Detalle");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));
        jPanel4.add(drDetalleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 160, 20));

        jLabel10.setText("Cuenta");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));
        jPanel4.add(drCuentaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, 150, 20));

        jLabel7.setText("Cliente");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, -1, -1));
        jPanel4.add(drClienteLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, 160, 20));

        jTabbedPane1.addTab("Depósito/Retiro", jPanel4);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 685, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void insertCedulaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertCedulaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_insertCedulaTextFieldActionPerformed

    private void insertNombreTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertNombreTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_insertNombreTextFieldActionPerformed

    private void insertClientButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertClientButtonActionPerformed
        clientBiz.insertClient(insertCedulaTextField.getText().toString(), insertNombreTextField.getText().toString(), insertApellidosTextField.getText().toString(), insertDireccionTextField.getText().toString(), insertFechaTextField.getText().toString());
        fillClientsTable();
    }//GEN-LAST:event_insertClientButtonActionPerformed

    private void updateClientButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateClientButtonActionPerformed
        clientBiz.updateClient(insertCedulaTextField.getText().toString(), insertNombreTextField.getText().toString(), insertApellidosTextField.getText().toString(), insertDireccionTextField.getText().toString(), insertFechaTextField.getText().toString());
        fillClientsTable();
    }//GEN-LAST:event_updateClientButtonActionPerformed

    private void borrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarButtonActionPerformed
        hasBiz.deleteHasByIdClient(insertCedulaTextField.getText().toString());
        clientBiz.deleteClient(insertCedulaTextField.getText().toString());
        fillClientsTable();
    }//GEN-LAST:event_borrarButtonActionPerformed

    private void clientTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clientTableMouseClicked
        insertCedulaTextField.setText(clientTable.getValueAt(clientTable.getSelectedRow(), 0).toString().toString());
        insertNombreTextField.setText(clientTable.getValueAt(clientTable.getSelectedRow(), 1).toString().toString());
        insertApellidosTextField.setText(clientTable.getValueAt(clientTable.getSelectedRow(), 2).toString().toString());
        insertDireccionTextField.setText(clientTable.getValueAt(clientTable.getSelectedRow(), 3).toString().toString());
        insertFechaTextField.setText(clientTable.getValueAt(clientTable.getSelectedRow(), 4).toString().toString());
    }//GEN-LAST:event_clientTableMouseClicked

    private void insertAccountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertAccountButtonActionPerformed
        accountBiz.insertAccount(insertAccount.getText().toString(), insertInterno.getText().toString(), 0, monedaComboBox.getSelectedItem().toString());
        hasBiz.insertHas(accountClientsTable.getValueAt(accountClientsTable.getSelectedRow(), 0).toString(),
                accountClientsTable.getValueAt(accountClientsTable.getSelectedRow(), 1).toString() + " "
                + accountClientsTable.getValueAt(accountClientsTable.getSelectedRow(), 2).toString(),
                insertAccount.getText().toString(),
                insertInterno.getText().toString());
        fillAccountTable();

    }//GEN-LAST:event_insertAccountButtonActionPerformed

    private void accountClientsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountClientsTableMouseClicked
        labelAccountClient.setText(accountClientsTable.getValueAt(accountClientsTable.getSelectedRow(), 1).toString() + " " + accountClientsTable.getValueAt(accountClientsTable.getSelectedRow(), 2).toString());
    }//GEN-LAST:event_accountClientsTableMouseClicked

    private void accountTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountTableMouseClicked
        labelAccountClient.setText(" ");
        List<has> hasList = hasBiz.getHas();

        for (int i = 0; i < hasList.size(); i++) {
            if (hasList.get(i).getIdAccount().equals(accountTable.getValueAt(accountTable.getSelectedRow(), 0).toString())) {
                labelAccountClient.setText(hasList.get(i).getNameClient());
            }
        }
    }//GEN-LAST:event_accountTableMouseClicked

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        hasBiz.deleteHasByIdAccount(accountTable.getValueAt(accountTable.getSelectedRow(), 0).toString());
        accountBiz.deleteAccountById(accountTable.getValueAt(accountTable.getSelectedRow(), 0).toString());

        fillAccountTable();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void accountsMovementTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountsMovementTableMouseClicked
       
    }//GEN-LAST:event_accountsMovementTableMouseClicked

    private void movementTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_movementTableMouseClicked
      drIDLabel.setText(movementTable.getValueAt(movementTable.getSelectedRow(), 0).toString());
      drMontoLabel.setText(movementTable.getValueAt(movementTable.getSelectedRow(), 1).toString());
      drFechaLabel.setText(movementTable.getValueAt(movementTable.getSelectedRow(), 2).toString());
      drDetalleLabel.setText(movementTable.getValueAt(movementTable.getSelectedRow(), 3).toString());
      drCuentaLabel.setText(movementTable.getValueAt(movementTable.getSelectedRow(), 4).toString());
      drClienteLabel.setText(movementTable.getValueAt(movementTable.getSelectedRow(), 5).toString());
    }//GEN-LAST:event_movementTableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CRUD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ID;
    private javax.swing.JButton accionButton;
    private javax.swing.JTable accountClientsTable;
    private javax.swing.JTable accountTable;
    private javax.swing.JTable accountsMovementTable;
    private javax.swing.JButton borrarButton;
    private javax.swing.JTable clientTable;
    private javax.swing.JLabel drClienteLabel;
    private javax.swing.JLabel drCuentaLabel;
    private javax.swing.JLabel drDetalleLabel;
    private javax.swing.JLabel drFechaLabel;
    private javax.swing.JLabel drIDLabel;
    private javax.swing.JLabel drMontoLabel;
    private javax.swing.JTextField insertAccount;
    private javax.swing.JButton insertAccountButton;
    private javax.swing.JTextField insertApellidosTextField;
    private javax.swing.JTextField insertCedulaTextField;
    private javax.swing.JButton insertClientButton;
    private javax.swing.JTextField insertDireccionTextField;
    private javax.swing.JTextField insertFechaTextField;
    private javax.swing.JTextField insertInterno;
    private javax.swing.JTextField insertNombreTextField;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane17;
    private javax.swing.JScrollPane jScrollPane18;
    private javax.swing.JScrollPane jScrollPane19;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private javax.swing.JTable jTable6;
    private javax.swing.JTable jTable7;
    private javax.swing.JTable jTable8;
    private javax.swing.JTable jTable9;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JLabel labelAccountClient;
    private javax.swing.JComboBox<String> monedaComboBox;
    private javax.swing.JTable movementTable;
    private javax.swing.JButton updateClientButton;
    // End of variables declaration//GEN-END:variables
}
